### ISSUE TITLE
Breaking change to addChild between 3.0 and 3.1

### ISSUE THREAD

**Issue by TyLindberg** [donmccurdy/glTF-Transform#1025]
**Describe the bug**
In v3.1.0+ using `addChild` to change the parent of a node from the scene to another node no longer seems to work. The node will remain a child of the scene after the `addChild` call.

**To Reproduce**
The following code will print `1` on `3.0.0` and `2` on `3.1.0`.

```js
import { NodeIO } from "@gltf-transform/core";

(async () => {
  const io = new NodeIO();
  const doc = await io.read("DamagedHelmet.glb");

  const newRootNode = doc.createNode("test");
  const scene = doc.getRoot().getDefaultScene();
  const childNode = scene.listChildren()[0];
  scene.addChild(newRootNode);
  newRootNode.addChild(childNode);

  console.log(scene.listChildren().length);
})();
```

The behavior can be made identical by adding `scene.removeChild(childNode)` to the above snippet.

**Expected behavior**
I would expect there to only be one child node to the scene in both versions.

**Versions:**
 - Version: 3.1.0+
 - Environment: Node.js

**Comment by donmccurdy** [comment]
Hm, thanks for flagging this! Appears to be an unplanned side effect of https://github.com/donmccurdy/glTF-Transform/pull/833. I agree it should be fixed for the v3.x lifecycle, but will need to think about whether it's feasible to keep in place for 4.x beyond that.

**Comment by donmccurdy** [comment]
Published fix to v3.4.7, thanks!

**Comment by TyLindberg** [comment]
Of course!

It's definitely an interesting question on what the long term behavior should be. My initial inclination is that adding nodes to multiple scenes should be an explicit operation, potentially though an additional parameter to `addChild`. However, I definitely don't have full scope over the implications of different options.

**Comment by donmccurdy** [comment]
I'm torn between:

(A) glTF Transform should automatically remove nodes from previous parents *if* those parents are no longer valid under the glTF spec.

(B) glTF Transform should do no more than necessary in addChild, and expect (warn?) the user to do that cleanup, perhaps with some utility function.

Previously it was attempting (A), but with overly-conservative requirements that prevented some valid glTF documents from loading (see https://github.com/donmccurdy/glTF-Transform/issues/831). Now I think it's really doing (A). If that turns out to be fragile or hard to maintain I may switch to (B), otherwise it will probably stay as it is...
