### ISSUE TITLE
`generator` is already set to gltf-transform when only reading file, not writing it

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#1036]
**Describe the bug**
I'm looking at using gltf-transform for some analysis of files in node.js. However, it looks like gltf-transform already modifies data on read - for example, asset.generator is already set to "glTF-Transform 3.4.8". This is a bit unexpected, I would assume that the generator changes somewhere before write, not on read.

**To Reproduce**
1. Read a file with `const doc = await io.read(file);`
[AlphaBlendModeTest.glb.zip](https://github.com/donmccurdy/glTF-Transform/files/12139183/AlphaBlendModeTest.glb.zip)

2. Check the generator with `doc.getRoot().getAsset().generator`
3. Note the generator is shown as glTF-transform for each asset, independent of actual generator

**Expected behavior**
Shows the actual generator. (gltf.report does in fact show the actual generator)

**Versions:**
 - Version: [3.4.8]
 - Environment: [Node.js]

**Additional context**
Not sure if there are other properties that glTF-transform modifies on read.

**Comment by donmccurdy** [comment]
Context

- https://github.com/donmccurdy/glTF-Transform/issues/385
- https://github.com/donmccurdy/glTF-Transform/pull/386

I don't strictly view this as a bug - the Document is not intended to "be" the raw glTF file on disk, it is an in-memory representation for processing, and has been decompressed, de-interleaved, and possibly optimized... at what point does the generator change during optimization? Also see: [Ship of Theseus](https://en.wikipedia.org/wiki/Ship_of_Theseus). 😅

 Importantly, I do intend for people to be able to implement their own pipeline *using* glTF Transform, defining the generator string themselves, and so I think overwriting the generator string in write() creates worse problems than setting it in read().

gltf.report avoids the issue by first calling [`readAsJSON`](https://gltf-transform.dev/modules/core/classes/NodeIO#readAsJSON), checking the generator and extensions. This also allows the CLI to still show some useful information in the `inspect` command even for files containing unsupported extensions. The generator is only set once the whole thing is unpacked into an in-memory Document.

Is this creating a problem for you? I think the expected behavior you describe is not the behavior I want by default, but I'm open to creating an opt-in setting for it.

**Comment by hybridherbst** [comment]
> at what point does the generator change during optimization
I get what you mean, but I think in this context here it would be: on the first operation, whatever it may be, even a direct write out! But not on `await io.read(file)`.

> gltf.report avoids the issue by first calling [readAsJSON](https://gltf-transform.dev/modules/core/classes/NodeIO#readAsJSON)
That's very helpful and certainly solves my issue here - I may have mis-read the docs or maybe they could be a bit more clear:
<img width="538" alt="image" src="https://github.com/donmccurdy/glTF-Transform/assets/2693840/3f116042-5895-4c4d-b3d8-b5f740f1e017">
I think the key here is "without parsing" which implies that the _other_ method, `read`, does parsing, not necessarily modifications. Maybe "unpacking" could be a helpful term here, but I understand if you don't want to change it.

**Comment by donmccurdy** [comment]
Maybe there's a case to be made that the `asset` entry doesn't belong in the in-memory "Document" representation at all, and should just be optionally specified when writing the file. The `generator` and `version` values are not easy to define, outside the context of a fully-encoded glTF file.

That'd be a breaking change though, and so probably not something I'd rush. I am certainly open to additions in the documentation.
