### ISSUE TITLE
Bad quality for texture compressed with default `etc1s` command

### ISSUE THREAD

**Issue by marwie** [donmccurdy/glTF-Transform#1062]
**Describe the bug**
Compressing the metallic-roughness texture with etc1s results in terrible quality

**To Reproduce**
1. Download zip [watch.zip](https://github.com/donmccurdy/glTF-Transform/files/12327580/watch.zip)
2. Run ` gltf-transform etc1s "Watch.glb" "Watch.etc1s.glb`

**Expected behavior**
Better texture quality 😅   
screenshot below is compressed with https://github.khronos.org/glTF-Compressor-Release/ default etc1s settings
![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/f11a2dd2-a754-4cbe-8d8f-911a7e4db8c3)

**Versions:**
 - Version: 3.5.1
 - Environment: cli

**Additional context**

Before compression
![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/cb1fc003-cce1-46fa-a172-b427fe388cda)

After compression
![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/f0093a39-6278-4343-8eee-6a8962b07370)

**Comment by hybridherbst** [comment]
We're so far pretty happy with the default settings for ETC1S, and the file and GPU size savings are so considerable that they offset the quality in almost all cases.
(That being said, we do provide a choice for people inside Needle Engine compression for what slots should be compressed with what)

This texture absolutely seems to be an outlier – it's the first time we see ETC1S go so horribly wrong. Yes, there can be artifacts, but not something that looks like 128px downsampling...
Do you know where this should be reported upstream? The ktxtools repo? Ideally defaults between different Khronos projects should probably match

**Comment by donmccurdy** [comment]
As far as I can see, the ETC1S default settings in the new Khronos glTF Compressor for web are essentially identical to what glTF Transform uses, with one exception — the web app doesn't generate mipmaps, probably because [libktx does not support them](https://github.com/KhronosGroup/KTX-Software/issues/464).

If we test the `toktx` command above, omitting the `--genmipmap` flag, you'll get the full quality back. That's certainly a surprise to me. I'm not sure why generating mipmaps should affect the quality _at all_, much less affect it so heavily.

glTF Transform doesn't expose the option to disable mips, though I'm open to doing that. But it'd be great to figure out why mipmaps matter here, and whether that's a bug. Perhaps a bug report on the KTX-Software repository would be a good next step, yes.

**Comment by hybridherbst** [comment]
That's great additional info, thanks for checking. 

So basically the bug seems to be that with mipmaps enabled, the highest mipmap (and all lower ones) change content, whereas an identical highest mipmap to "no mipmaps" would probably be expected. I'll report that to the KTX-Software repo.

**Comment by hybridherbst** [comment]
Some additional findings related to gltf.report: it looks like there _is_ an ok-ish mip 0 in the file, but mips degrade very fast. Seems that gltf.report doesn't display mip 0 but instead uses a lower mip (which I think is fine because the displayed image is small), and that lower mip is broken for this file.

**Comment by donmccurdy** [comment]
Seems to be nothing we can do on this side, upstream discussion in:

- https://github.com/KhronosGroup/KTX-Software/issues/759

**Comment by hybridherbst** [comment]
Do you want to continue the discussion regarding the --assign-oetf command in the ktx-software repo? I'm confused by Mark and your answer collliding, and especially that without the `--assign-oetf linear` part the texture still comes out correct but looks much better.
