### ISSUE TITLE
Meshopt compression breaks normals and/or tangents on mesh

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#1142]
**Describe the bug**
A specific model ends up looking wrong only after meshopt compression. Draco compression seems fine (but actually increases model size, maybe there are sparse accessors?)

**To Reproduce**
1. Download https://drive.google.com/file/d/1EV5S5x3cJlz2NBOFfiMtLZwwnnyoHgv-/view?usp=sharing
2. Check the meshopt version in any viewer, note that something's wrong with tangents or normals (not sure yet)
3. Check the original version, that's fine; draco is also fine

| Original | Meshopt |
| - | - |
| <img width="499" alt="image" src="https://github.com/donmccurdy/glTF-Transform/assets/2693840/11ae811c-956e-4982-a580-841ab56408d9"> | <img width="424" alt="image" src="https://github.com/donmccurdy/glTF-Transform/assets/2693840/af5c9ac9-9dc5-4ede-aece-e8d651eeb6c7"> |

**Expected behavior**
Proper surface behavior after meshopt compression.

**Versions:**
 - Version: v3.5.7
 - Environment: CLI

**Comment by zeux** [comment]
FWIW I looked into something like this before in an issue with glTF-Transform that was reported on gltfpack but I forgot to post a parallel issue here, and the problem there was due to glTF-Transform not clamping the morph normal deltas during quantization to a -1..1 range. Clamping them isn't perfectly accurate in certain cases but it usually leads to good results, whereas not clamping them risks integer overflow which completely changes normal direction. This is specific to morph targets. Draco doesn't support morph target compression period so it's not surprising that you see no improvement here.

See https://github.com/zeux/meshoptimizer/issues/515#issuecomment-1735402099. I think the problem in glTF-Transform was in MathUtils quantization code.

**Comment by zeux** [comment]
(something else to make sure is that glTF-Transform uses octahedral filters for base mesh normals but no filters on normal deltas, as octahedral filters only apply to normalized vectors; I haven't verified if this is the case so I don't know if this is a problem but I assume this would be discovered earlier)

**Comment by donmccurdy** [comment]
Published a fix to v3.8 — thank you @hybridherbst for the report. @zeux I really appreciate the comments! You're correct on both issues, and saved me a lot of time tracking the causes down.
