### ISSUE TITLE
Support for KTX-Software upcoming release

### ISSUE THREAD

**Issue by krispya** [donmccurdy/glTF-Transform#1163]
As of [July](https://github.com/KhronosGroup/KTX-Software/releases/tag/v4.3.0-alpha3), `toktx` is deprecated in favor of `ktx create`. This is especially critical for proper format conversion, for example HDR textures.

**Comment by donmccurdy** [comment]
Currently that's still an alpha, and the July release had a number of important bugs. I think they've fixed those bugs on `main`, but haven't cut a new release since then. I do intend to switch over to `ktx create` when the KTX Software release reaches stable or perhaps even beta status, but I'm not sure what the timeline is for that.

Related:

- #1038
- #675
