### ISSUE TITLE
Missing required extension, "CESIUM_RTC".

### ISSUE THREAD

**Issue by jinjun1994** [donmccurdy/glTF-Transform#1218]
**Describe the bug**
read glb error

**Comment by donmccurdy** [comment]
Hi @jinjun1994! glTF Transform supports all Khronos-ratified extensions to the glTF format, and a number of other multi-vendor extensions listed below:

- https://gltf-transform.dev/extensions

`CESIUM_RTC` is an extension created by Cesium, which I expect is only currently understood by Cesium's own software. In order to limit the complexity of glTF Transform, and to ensure I have time and resources to maintain the project, I'm not currently adding vendor-specific extensions myself.

To read this file you may need to either (a) find a way to create the file without that extension, or (b) create an implementation of the extension using glTF Transform's extension API. As described in the link above, glTF Transform allows anyone to implement their own extensions, register the extensions with the I/O classes, and then read/write and process the extensions using the rest of the glTF Transform library.
