### ISSUE TITLE
Join command runs out of memory

### ISSUE THREAD

**Issue by thecatontheflat** [donmccurdy/glTF-Transform#1317]
**Describe the bug**
After eating 31GB of RAM the process gets OOM-killed

**To Reproduce**
1. Install v4 alpha
```
npm install --global @gltf-transform/cli@next @gltf-transform/core@next @gltf-transform/extensions@next @gltf-transform/functions@next
```

2. Download the attached GLTF (700MB unpacked)
https://www.dropbox.com/scl/fi/q1uisxtqoe7hj4d5gzm1r/world.zip?rlkey=1gt9q5t4ns9v8xwwx8gy6geo2&dl=0

3. Run the following command to join meshes
```
gltf-transform join world.gltf world-transformed.glb
```

4. OOM Killed 💀 

**Versions:**
 - Version: 4.0.0-alpha.10
 - Environment: node

**Comment by donmccurdy** [comment]
Thanks for the report, @thecatontheflat! I think this issue has the same root cause as #1315, so I'm going to merge the two issues. If you need a workaround in the meantime, I found that running `weld` first, followed by `join`, will complete. The weld step is slow, but keeps a more reasonable memory footprint for a file this size.

**Comment by thecatontheflat** [comment]
The workaround has worked! Thanks for the suggestion!
