### ISSUE TITLE
Object transforms look off after using Instance

### ISSUE THREAD

**Issue by Kyozon** [donmccurdy/glTF-Transform#1509]
**Describe the bug**
The resulting .gltf scene looks off when using the `gltf-transform instance`.

**To Reproduce**
1. Download: [merged.zip](https://github.com/user-attachments/files/17120741/merged.zip)

2. Import `merged.gltf` into Blender and verify original transforms as seen in the image below:

![Default](https://github.com/user-attachments/assets/7102a7a8-3cf4-4b18-8bb9-a6d594602369)

3. Use `gltf-transform instance merged.gltf instanced.gltf`

4. Import `instanced.gltf` into Blender and verify the bug as seen in the image below:

![Instance](https://github.com/user-attachments/assets/f6c8d85a-70bc-422a-a9cd-104f40acb332)

**Expected behavior**
Retain the original transforms but optimize the scene to use GPU instances. 

**Versions:**
 - Version: 4.0.8
 - Environment: Node.js CLI

**Comment by donmccurdy** [comment]
Hi @Kyozon! The instanced scene looks correct to me, both in Blender and in https://gltf-viewer.donmccurdy.com/. Could you confirm if you're seeing the problem both in Blender and in my viewer, and perhaps share the 'broken' copy of the model as well? 

![CleanShot 2024-09-24 at 16 40 19@2x](https://github.com/user-attachments/assets/459089a5-cded-435c-87b5-dcfd05102789)

**Comment by Kyozon** [comment]
Hi @donmccurdy. Thank you for the quick reply! 

Sure, here is the broken file: [Instanced.zip](https://github.com/user-attachments/files/17121000/Instanced.zip)

**Comment by donmccurdy** [comment]
Hm... something is weird in the source file:

```jsonc
  "buffers": [
    {
      "uri": "glTF.bin",
      "byteLength": 8160
    },
    {
      "uri": "glTF.bin",
      "byteLength": 8160
    },
    {
      "uri": "glTF.bin",
      "byteLength": 8160
    }
  ],
```

Three buffers, all pointing at the same thing... I'm not sure whether it's technically valid in the glTF spec, but the pygltflib authors probably didn't intend that, and it's leading to data loss here. 

I'll have to think a bit about the best way to handle it, but in the meantime, you can avoid the issue by exporting to `.glb` instead of `.gltf`.

**Comment by donmccurdy** [comment]
Fixed in #1511. With these changes glTF Transform will log a warning (`Duplicate resource URI, "glTF.bin"`) but will continue to process the file. When writing to `.gltf`, the additional buffers will be written as separate files with unique names. In this case:

- merged.gltf
- merged_1.bin
- merged_2.bin
- glTF.bin

To consolidate the binary data and avoid extra files, either write to .glb or use the [`unpartition()`](https://gltf-transform.dev/modules/functions/functions/unpartition) function.



![instanced 3D letters, no bugs](https://github.com/user-attachments/assets/3f8241bd-79a3-4c93-9907-aeb50db81777)

**Comment by donmccurdy** [comment]
Reverting #1511 and reopening the issue. Original approach to fixing the issue will cause other problems.

**Comment by donmccurdy** [comment]
New attempted change in #1522. Unfortunately not a "fix", but will throw a clear error if conflicting buffer URIs are going to break the file. To workaround it will still be necessary to write to .glb or use the [unpartition()](https://gltf-transform.dev/modules/functions/functions/unpartition) function.
