### ISSUE TITLE
Use nodejs's builtin fetch

### ISSUE THREAD

**Issue by rotu** [donmccurdy/glTF-Transform#1531]
Node has a `fetch` function built in, so `NodeIO` should no longer need a third party library.

**Comment by donmccurdy** [comment]
My goal is for glTF Transform to support all stable versions of Node.js — currently v18, v20, and v22. It looks like the Node.js `fetch` function is stable only in v22+, so I don't think we should access it automatically in NodeIO quite yet. But we could certainly upgrade the documentation to use built-in fetch rather than `node-fetch`, passing that into the NodeIO constructor. I believe this would just require an update to the documentation here:

https://github.com/donmccurdy/glTF-Transform/blob/7aa92bea25d775dea3fd067e6bdfe0eb078849ac/packages/core/src/io/node-io.ts#L31-L42

**Comment by donmccurdy** [comment]
Node.js v20 has reached EOL, removing `node-fetch` from CLI dependencies:

- https://github.com/donmccurdy/glTF-Transform/pull/1838
