### ISSUE TITLE
UASTC option returning error

### ISSUE THREAD

**Issue by haydeng21** [donmccurdy/glTF-Transform#181]
Hey, Don! In the past I've used gltf-pipeline for draco compression and the basisu command line to create basis textures, then programmatically applied the basis textures. I recently found gltf-transform and I'm a huge fan! Thanks for building an awesome tool. 

I've been experimenting with gltf-transform this morning and have a few questions and 1 issue. Here's the model for reference:

[Skateboard.zip](https://github.com/donmccurdy/glTF-Transform/files/5937357/Skateboard.zip)

**Issue:**

`gltf-transform uastc Skateboard.glb gltf-transform/Skateboard.glb`
This command is not working for me and returns `Texture compression failed.`. The etc1s option works. For reference, the uastc command works for me with the toktx cli. I used it on the 3D-B.jpg and successfully received a ktx2 file. However, something is wrong because it doesn't work in your gltf-viewer (the texture showed up black) and it also doesn't work in PVRTexTool. Unfortunately the etc1s version of 3D-B texture has horrible quality, even with highest quality settings, so I was wanting to try uastc. Any guidance? Probably not the case but could this issue be something to do with this texture not being square?

**Questions:**

Could you provide any suggestions about converting normal maps to ktx2 and maintaining quality? I read about the `-separate_rg_to_color_alpha` option on the basisu github page but seems like I'd have to stick with programmatically applying .basis textures instead of embedding the ktx2 texture? *"For tangent space normal maps, you should separate X into RGB and Y into Alpha, and provide the compressor with 32-bit/pixel input images. Or use the "-separate_rg_to_color_alpha" command line option which does this for you. The internal texture format that Basis Universal uses (ETC1S) doesn't handle tangent space normal maps encoded into RGB well. You need to separate the channels and recover Z in the pixel shader using z=sqrt(1-x^2-y^2)."* Maybe It's an issue with the encoding, does gltf-transform auto set the texture encoding to linear on normal maps?

When exporting a model from blender to be used in three.js, what is your normal pipeline of optimizations? I'm guessing you run a sequence of gltf-transform commands and then maybe others? Do you also use gltfpack? I just learned about it and am interested in testing it out but it seems more intense than gltf-transform and like it may cause some issues with three.js?

**Comment by donmccurdy** [comment]
> This command is not working for me and returns "Texture compression failed".  The etc1s option works. 

Looks like this is caused by https://github.com/KhronosGroup/KTX-Software/issues/360. 

> Probably not the case but could this issue be something to do with this texture not being square?

The dimensions in this model (128x512 and 1024x1024) look fine, they don't need to be square, just powers of two on both sides.

> Could you provide any suggestions about converting normal maps to ktx2 and maintaining quality? ... does gltf-transform auto set the texture encoding to linear on normal maps?

This tool does set the texture encoding to linear wherever that's required. The ETC1S format doesn't work very well with normal 3-channel normal maps, which is what three.js or glTF currently support. The suggestion from the Basis docs is for two-channel normal maps, so you'd need to customize three.js shaders to support that.

You might get a better results by upscaling the texture before compressing it with ETC1S. Or UASTC tends to work better for this case. Or you could leave the normal maps in PNG format.

> When exporting a model from blender to be used in three.js, what is your normal pipeline of optimizations? ... Do you also use gltfpack? ... it seems more intense than gltf-transform and like it may cause some issues with three.js?

Probably depends on the starting point of your models. If they're made by an artist with your application in mind, you probably don't want to change their structure very much, but just to optimize the compression of geometry and textures. If they're coming from a 3D library like Sketchfab or TurboSquid, the artist often hasn't optimized much, and so the model's structure is often pretty messy and inefficient.

gltfpack is _very_ good at dealing with the second — it'll optimize almost everything, automatically, and offers several great optimizations that glTF-Transform does not. The only downside is it's a bit opinionated, and might cause structural changes you don't want in a model you've set up a specific way (e.g. nodes, vertices, and keyframes will get simplified).

glTF-Transform is more targeted — you can pick one specific optimization and just do that: deduplicate data, compress textures, resample animation, add vertex tangents, etc... but this also means you have to inspect the model more and figure out what needs to be done. 

If you want to use both, just be sure to use gltfpack _second_ if you're using its compression options. glTF-Transform can't read/write the compressed gltfpack data, although `gltf-transform gzip input.glb` still works. I'm not aware of any issues using gltfpack and three.js together, that should be OK. Be sure to add gzip after using gltfpack, they go together quite well.

**Comment by donmccurdy** [comment]
I'll leave this open as a bug in the CLI — I think it should at least report the underlying error from KTX-Software.

Documentation about generally-recommended optimizations is a good idea too but that's a big and complicated topic. 😅

**Comment by lexaknyazev** [comment]
FWIW, our upcoming texture guidelines specifically suggest 8-bit inputs for texture compression to avoid unexpected behavior.

**Comment by donmccurdy** [comment]
Assuming the outcome on https://github.com/KhronosGroup/KTX-Software/issues/360 will be to show a warning, rescale, and continue exporting, I will try to make sure that warning is also visible to users doing compression through glTF-Transform.

If the original file (from DCC software, Sketchfab, etc.) is already 16-bit, it doesn't sound like there's any reason a user should need to manually convert the textures before running them through KTX-Software though.

**Comment by lexaknyazev** [comment]
> it doesn't sound like there's any reason a user should need to manually convert the textures before running them through KTX-Software

It depends.

Let's say there's a very long object and its real roughness values slowly go from `0.0` to `1.0` (i.e. forming a gradient). Storing them with 16-bit PNG (and rendering using 16-bit normalized texture type, see `EXT_texture_norm16` for WebGL) would provide steps as small as `1/65535` that may look noticeably better than `1/255` 8-bit quantization.

Given that both Basis Universal codecs are 8-bit at best, it's important to assess compression quality by comparing with uncompressed 8-bit RGBA rather than with arbitrary DCC input.

**Comment by donmccurdy** [comment]
I believe all of that is true _if_ the original texture had any actual business being a 16-bit PNG.

Most users of this tool will not know what a 16-bit PNG is, and whether they have an 8-bit or 16-bit PNG in the glTF file to begin with was probably an arbitrary decision of some authoring tool that optimizes for lossless reproduction and applies the same choice to every texture. For an extreme example, models from Sketchfab sometimes use 4K textures to represent a single solid color, because the artist only cares that the model looks correct in Sketchfab, and is relying on Sketchfab to optimize for performance.

From that perspective, I think tools like glTF-Transform and KTX-Software go ahead with lossy compression, but show a clear and actionable warning about what they're doing — this way users know where to start debugging if quality loss is noticeable. It looks like Mark's changes to KTX-Software will include a more helpful warning here, too.

**Comment by haydeng21** [comment]
@donmccurdy Awesome, I'll be watching for the updates to KTX-Software and gltf-transform to handle the 16-bit texture issue with UASTC. Thank you very very much for all this helpful information regarding model optimizations! Going to start playing with gltfpack 🤗

**Comment by haydeng21** [comment]
@donmccurdy I've been trying to use gltf-transform to draco compress and/or basis compress textures and then run the gltfpack default compression on the model but it returns errors `file requires Draco mesh compression support` and/or `file requires BasisU texture support`. So maybe neither of these tools are compatible with each other? Or I'm just doing something wrong? Not a big deal either way, just curious.

**Comment by donmccurdy** [comment]
Draco compression and gltfpack's Meshopt compression are mutually exclusive, and if you're using one you can't use the other. If you're planning to use gltfpack I would avoid using Draco compression before that. If you're comparing both to decide, be sure to compare the gzipped sizes rather than the raw sizes.

I'm surprised gltfpack doesn't allow BasisU textures as inputs, though. That seems like it should probably be reported as a feature request on its repository.

**Comment by haydeng21** [comment]
@donmccurdy Okay gotcha, sorry, I'm not very familiar with all this compression. Is there any runtime advantage to gltpack's Meshopt compression vs draco besides potentially smaller file size? I see that I need to do `GLTFLoader.setMeshoptDecoder` for it to work anyways - that error occurred in your gltfviewer by the way. 

Also, I've gzipped the glb file but I'm not able to correctly load it in three.js. I'm looking into this more now but any light you can shed on that issue? Error is `Unexpected token  in JSON at position 0`

**Comment by haydeng21** [comment]
I just ran gltf-transform draco compression vs. gltfpack compression with the -cc option and gzip. Draco bin file comes out to 146kb and the gltfpack .bin file comes out to 176kb

**Comment by donmccurdy** [comment]
> Is there any runtime advantage to gltpack's Meshopt compression vs draco besides potentially smaller file size? 

I think Draco tends to compress geometry a bit further, but it only compresses geometry. MeshOpt will also compress animations and morph targets, and decompresses faster during loading (or did, the last time I checked). In either case you'll need to register the right decoder with THREE.GLTFLoader. For small files you might not notice much difference between the two.

My viewer doesn't support Meshopt compression just yet.

> Also, I've gzipped the glb file but I'm not able to correctly load it in three.js.

With gzip you usually don't directly load the `.glb.gz` URL — you go ahead and request the `.glb` version, and then many (but not all) web servers are configured to automatically serve the `.glb.gz` version instead. The browser will automatically decompress the gzipped data for you, so nothing is done differently in GLTFLoader.

**Comment by haydeng21** [comment]
Wonderful, thanks for all the explanations. I learn so much from you. You're truly the man @donmccurdy! Thanks again
