### ISSUE TITLE
Crash on CLI operation: gltf-transform draco with large mesh

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#198]
I'm getting
`error: abort(undefined). Build with -s ASSERTIONS=1 for more info.`
when trying to draco-compress a large (1 GB) mesh. The error doesn't happen immediately but after ~30min or so.

I've sent a download link to the mesh to your mail address.

Full log:
```
gltf-transform draco .\035-2.1.etc1s.glb .\035-2.1.etc1s+draco.glb --verbose
debug: weld: Complete.
debug: [KHR_draco_mesh_compression] Compression options: {"method":1,"encodeSpeed":5,"decodeSpeed":5,"quantizationBits":{"POSITION":14,"NORMAL":10,"COLOR":8,"TEX_COORD":12,"GENERIC":12}}
undefined

error: abort(undefined). Build with -s ASSERTIONS=1 for more info.
```

**Comment by donmccurdy** [comment]
Just to check, what version of glTF-Transform are you using?

I'm getting weird results here, on the latest version of glTF-Transform:

- glTF-Transform, default settings: Same error as you. Seems like an OOM, either in Node.js or the WASM Draco Encoder. I think the error is emitted from WASM.
- glTF-Pipeline: Successfully compresses the file in 2-3 minutes, down to 500 MB.
- glTF-Transform, with `--encodeSpeed=10`: Successfully compresses the file in 20 minutes, down to 380 MB.

That doesn't make much sense to me, I would have expected `--encodeSpeed=10` to give worse compression than whatever glTF-Pipeline is doing, since it's trading encode speed for compression. Maybe glTF-Pipeline is using an older version of the Draco library. I'd be curious if you get the same results, but this seems like something related to the Draco encoder itself.

Aside — technically I increased node.js memory when testing this, but I'm not really sure it is doing anything or affecting WASM memory allocation, so you (hopefully) don't need to do the same. But if so, you can run this from the project root after doing a local build:

```
node --max-old-space-size=8192 packages/cli/bin/cli.js draco input.glb output.glb --verbose --encodeSpeed=10
```

**Comment by donmccurdy** [comment]
Seems to be a function of Draco encoder version and Node.js / WASM resources for larger meshes; the Draco team might have more ideas but I don't think there's much I can do on this one. Increasing `--encode-speed` seems to decrease encoding resources, which may help.
