### ISSUE TITLE
Consider adding ktx-fix command

### ISSUE THREAD

**Issue by lexaknyazev** [donmccurdy/glTF-Transform#218]
Older versions of `toktx` tool produce KTX files with incorrect color primaries value for non-color textures. Although this difference doesn't affect current clients, it is not conformant per the BasisU glTF extension spec. A simple command powered by KTX-Parse would be enough to fix that.

**Comment by donmccurdy** [comment]
This refers to the proposed changes in https://github.com/donmccurdy/glTF-Transform/issues/215, I assume? Do you know the specific DFD values we'd need to look for and edit, rather than the `toktx` flags?

If it's just DFD changes then I agree it's very easy, and could just be done automatically (showing a warning) when reading/writing a file through this tool, without even adding a new command.

/cc @MarkCallow

**Comment by lexaknyazev** [comment]
The DFD's `colorPrimaries` field for non-color textures should be set to zero (unspecified).
