### ISSUE TITLE
Feature: --format for gltf-transform validate

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#231]
The validate command currently doesn't support the same formatting options as inspect.

Reasoning for having this here (instead of using the gtlf-validator package directly) would be that the gltf-validator package does not have a CLI option, and it's great to have gltf-transform as go-to swiss army knife :) We're currently calling it from C# and wrapping the CLI.

An additional question: do you think a fourth formatting option with JSON output would make sense, for both validate and inspect? Ideally that would match https://github.khronos.org/glTF-Validator/.

(I might be able to take a stab at a PR; main questions would be: is this in scope? where would shared formatting methods move to?)

**Comment by donmccurdy** [comment]
Definitely "in scope" from my perspective! The CLI has a few common formatting functions here:

https://github.com/donmccurdy/glTF-Transform/blob/1e1a5c3775b8e64eaa123852d34971b000ee8f16/packages/cli/src/util.ts#L20-L48

And then perhaps `formatTable(...)` should be moved to a shared export too:

https://github.com/donmccurdy/glTF-Transform/blob/1e1a5c3775b8e64eaa123852d34971b000ee8f16/packages/cli/src/inspect.ts#L87-L107

One consideration. At the moment the `validate` command prints four separate tables (example below). The `inspect` command does something similar, necessary there because each table has different columns. _Ideally_ the CSV output for `validate` would be a fully-valid CSV file, i.e. merging all severity levels into a single table. Does that sound OK for your goals?

```
 ERROR
 ────────────────────────────────────────────
info: No errors found.



 WARNING
 ────────────────────────────────────────────
info: No warnings found.



 INFO
 ────────────────────────────────────────────
┌────────────┬─────────────────────────┬──────────┬──────────┐
│ code       │ message                 │ severity │ pointer  │
├────────────┼─────────────────────────┼──────────┼──────────┤
│ NODE_EMPTY │ Empty node encountered. │ 2        │ /nodes/0 │
├────────────┼─────────────────────────┼──────────┼──────────┤
│ NODE_EMPTY │ Empty node encountered. │ 2        │ /nodes/3 │
└────────────┴─────────────────────────┴──────────┴──────────┘



 HINT
 ────────────────────────────────────────────
info: No hints found.
```
