### ISSUE TITLE
Node.setMatrix() support

### ISSUE THREAD

**Issue by VelocityRa** [donmccurdy/glTF-Transform#270]
How come this is not supported? There's already a `Node.getMatrix`.

I'm seeing a bug that I think is related.
Using [gl-matrix](https://github.com/toji/gl-matrix), I have a `mat4` and doing this (which I have to do without a `setMatrix` - bunch of [useless calculation](https://github.com/toji/gl-matrix/blob/fccd5f707432ec5cc1774575be84c9f901a198d0/docs/mat4.js.html#L1207-L1300) and precision loss):
```ts
const getTRS = (m: mat4) => {
    return { t: mat4.getTranslation(vec3.create(), m), r: mat4.getRotation(quat.create(), m), s: mat4.getScaling(vec3.create(), m) };
};

const setNodeMatrix = (node: GLTFNode, mat: mat4) => {
    let trs = getTRS(mat);
    node.setTranslation([trs.t[0], trs.t[1], trs.t[2]]);
    // quat.normalize(trs.r, trs.r); // i get asserts either way
    node.setRotation([trs.r[0], trs.r[1], trs.r[2], trs.r[3]]);
    node.setScale([trs.s[0], trs.s[1], trs.s[2]]);

    console.log(mat, node.getMatrix());
    assert(mat4.equals(mat, node.getMatrix()));
}
```
I get asserts in some cases. Example:
```
[-0.9307078123092651, 0.36324116587638855, -0.04288084805011749, 0, -0.3623482286930084,  -0.9316428303718567, -0.02730146236717701,  0, -0.044879984110593796, -0.00888469722121954,  0.8988363742828369, 0, 310.8424987792969, -5155.25244140625, -366.21356201171875, 1]
[-0.9307281322940169, 0.3632646333314609,  -0.04257750763746079, 0, -0.36232478384586403, -0.9316375673397288, -0.028303744841263856, 0, -0.04495307531851036,  -0.009824320406136731, 0.8988229395637517, 0, 310.8424987792969, -5155.25244140625, -366.21356201171875, 1]
```
I can also see that exported meshes are transformed incorrectly compared to my obj exporter that transforms each vertex at export time with the raw matrices, which may be related to this. I don't know what _else_ it could be. The rest of the code is pretty much the same, and my nodes are placed on the root.

**Comment by donmccurdy** [comment]
I've had some trouble using `gl-matrix` to decompose matrices (https://github.com/toji/gl-matrix/issues/408) and so I don't use those functions internally. There's a (currently undocumented) `MathUtils.decompose(...)` function that follows the three.js implementation and this has worked much better for me with, e.g., conversions from other formats:

https://github.com/donmccurdy/glTF-Transform/blob/33a91aff3bfa281ee8fab60fd1d233b41bafd749/packages/core/src/utils/math-utils.ts#L60-L75

Does decomposition work correctly for your model with this approach?

***

As for whether a  `setMatrix(...)` method  should be added, I guess it comes down to what that method should do, if it were added?  One option is to decompose the matrix within that method, but of course this will give the same result as using `MathUtils.decompose` by yourself. Another option is store the matrix on the Node, which [currently only stores TRS properties](https://github.com/donmccurdy/glTF-Transform/blob/33a91aff3bfa281ee8fab60fd1d233b41bafd749/packages/core/src/properties/node.ts#L40-L44). This would create some uncertainty about what happens when `setTranslation` is called after `setMatrix`, and what should be put in the exported file, though — TRS properties or a matrix? Other users may prefer that TRS properties be used.

**Comment by VelocityRa** [comment]
> Does decomposition work correctly for your model with this approach?

Tried it, has the same result.

**Comment by VelocityRa** [comment]
Err, not the same result. `decompose` is noticeably more correct.

**Comment by VelocityRa** [comment]
> which currently only stores TRS properties.

Ouch. Is this a limitation of the spec?

**Comment by donmccurdy** [comment]
If you have an original GLB model with the matrices you mention, could you try running it through https://github.khronos.org/glTF-Validator/? The glTF spec allows setting `node.matrix` rather than TRS properties, as you mention, but [requires that the matrix always be decomposable to TRS](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#transformations). 

I'm open to adding a `setMatrix` method, but if the matrix you have is not decomposable, then this will unfortunately not fix anything here. If the matrix _is_ decomposable, then I would expect that `MathUtils.decompose(...)` can correctly decompose it, despite the possible issues in `gl-matrix`.

/cc @lexaknyazev FYI for relation to https://github.com/KhronosGroup/glTF-Validator/issues/164 and https://github.com/toji/gl-matrix/issues/408.

**Comment by VelocityRa** [comment]
It says ``The asset is valid.` Just some `UNUSED_OBJECT` warnings.

**Comment by donmccurdy** [comment]
Sorry, I guess I'm not sure what to do with this... Because certain cases require putting TRS into nodes, and the matrix is required to be decomposable anyway, I would ideally want to implement `setMatrix()` by decomposing it to the appropriate TRS properties. But if `MathUtils.decompose` is not giving the results you expect, I'm not sure that would help. I've already tried to make that method more robust than the `gl-matrix` equivalent.

**Comment by VelocityRa** [comment]
Ok, thanks anyway. Feel free to close this, or leave it open until/if you implement `setMatrix`.
