### ISSUE TITLE
Error: GLB must have 0–1 buffers. when writing glb after running partition

### ISSUE THREAD

**Issue by peteshand** [donmccurdy/glTF-Transform#279]
**Describe the bug**
After running partition on a gltf/glb and then trying to write to a glb I get the following error:
Error: GLB must have 0–1 buffers.

Writing to a GLTF works as expected

**To Reproduce**
```
const document = io.read(input);

document.createExtension(TextureBasisu)
    .setRequired(true);

await document.transform(functions.partition({ meshes: true }));

io.write(output, document); // error happens here
//also tried
var buffer = io.writeBinary(document); // error happens here
```

**Expected behavior**
Expected behavior would be for the write to no fail, unless I'm misunderstanding something

**Versions:**
 - Version: 0.11.4
 - Environment: Node.js

Addition Notes:
Related closed ticket: https://github.com/donmccurdy/glTF-Transform/issues/228

The buffer count check is happening in platform-io.ts
```
public writeJSON (doc: Document, _options: Partial<WriterOptions> = {}): JSONDocument {
	if (_options.format === Format.GLB && doc.getRoot().listBuffers().length > 1) {
		throw new Error('GLB must have 0–1 buffers.');
	}
	return GLTFWriter.write(doc, {
		format: _options.format || Format.GLTF,
		logger: _options.logger || this._logger,
		vertexLayout: _options.vertexLayout || this._vertexLayout,
		dependencies: {...this._dependencies, ..._options.dependencies},
		basename: _options.basename || ''
	} as Required<WriterOptions>);
}
```
However commenting this out results in the partition .bin files not being written

**Comment by donmccurdy** [comment]
The purpose of the `partition` command is to create separate buffers (i.e. external `.bin` files) for each mesh or animation. By convention a GLB file is usually self-contained, and doesn't reference external files, so GLTF is the output format you'd want to use for this case.

**Comment by peteshand** [comment]
Yeah right, I thought it would still technically be possible to have external .bin files and have the GLTF header info saved as a GLB binary.

Would there be any file size decrease when comparing:
`a GLTF with gzip ` and `a GLB with gzip`?
This is the main reason for this line of investigation.

**Comment by donmccurdy** [comment]
Technically the glTF format allows (or doesn't prohibit) these four arrangements:

1. GLTF with external resources
2. GLTF with embedded (ASCII / Base64) resources
3. GLB with external resources
4. GLB with embedded (binary) resources

This project can read all of 1–4, but supports writing only (1) and (4). It avoids (2) because the Base64 option is quite inefficient, and avoids (4) because of convention – I haven't seen other tools producing files that way and don't want to add confusion.

I don't expect there'd be any difference between GLTF+gzip or GLB+gzip, but some small differences are certainly possible.

**Comment by peteshand** [comment]
Cool, thanks for the clarification
