### ISSUE TITLE
how to read embedded glTF file by nodeIO

### ISSUE THREAD

**Issue by ligaofeng0901** [donmccurdy/glTF-Transform#310]
I upgraded glTF-Transform from version 0.8 to 1.2, then my project didn't work. I debugged and found that change:
the latest version
https://github.com/donmccurdy/glTF-Transform/blob/main/packages/core/src/io/node-io.ts#L94
version 0.8
https://github.com/donmccurdy/glTF-Transform/blob/v0.8.4/packages/core/src/io/node-io.ts#L110
In the latest code, the logic of testing whether the external resource uri is a data uri has been removed, so if the input file is embedded glTF, it doesn't work. I wonder why the feature is been removed, and if there's another way to do it.

**Comment by dbuck** [comment]
I also ran into this just recently, we were using obj2gltf saving as gltf without using the --separate flag in an early intermediate step before running through gltf-transform to do additional processing.

Changing to store that step as glb worked around the issue, but it can still be convenient for early debugging at times to use gltf !

**Comment by donmccurdy** [comment]
Looks like this was a regression caused by https://github.com/donmccurdy/glTF-Transform/pull/266 – added embedded Data URI support to the `readJSON` method, and must have broken it for another method. The logic was moved to the base i/o class:

https://github.com/donmccurdy/glTF-Transform/blob/a788bcface86071946e13a7fd669c87009cbfdcb/packages/core/src/io/platform-io.ts#L84-L89

Not intended, will take a look soon!

**Comment by donmccurdy** [comment]
Fix published as v0.12.5.
