### ISSUE TITLE
Request: Expose more options to etc1s

### ISSUE THREAD

**Issue by dbuck** [donmccurdy/glTF-Transform#318]
**Is your feature request related to a problem? Please describe.**
I'd like to disable threading during a etc1s toktx step using `--threads 1` because I'm using multiple processes to run the command in parallel. It looks like a simple addition if we just want to add the single param.

Would there be a possible desire / reasoning to allow forwarding any unknown --args to underlying executables for these possible steps which have a large number of exposed options?

**Comment by donmccurdy** [comment]
I'd left `--threads` out because it didn't seem to be working as expected, but I don't remember why that was. If you'd like to try adding the flag and confirming that it works for you, I'm OK with including it. 

I would rather not pass through unknown arguments, because in general I'm trying to avoid underlying executables entirely and don't want to get locked into them. It wasn't possible in this case (https://github.com/BinomialLLC/basis_universal/ did not include a KTX2 encoder yet) but eventually I'll be moving this tool away from requiring an external KTX-Software installation.

**Comment by dbuck** [comment]
Totally makes sense, and I can appreciate the desire to get rid of the external ktx-software dependency (Just spent too much time debugging that for a different issue!) ;)

Will open a PR when I can, thanks.

**Comment by donmccurdy** [comment]
Merging into https://github.com/donmccurdy/glTF-Transform/issues/358.

**Comment by dbuck** [comment]
Not quite the same effect I was after, I'll comment on the PR, they're missing a couple small nuances! thanks!
