### ISSUE TITLE
error: maxMemoryUsageInMB limit exceeded when resizing large jpeg textures

### ISSUE THREAD

**Issue by bennlich** [donmccurdy/glTF-Transform#344]
**Describe the bug**
Resizing large jpeg textures fails with `error: maxMemoryUsageInMB limit exceeded`.

**To Reproduce**
Run `gltf-transform resize --width 512 --height 512` on a model with an 8192x8192 jpeg texture.

**Additional context**
This seems to be an upstream bug in the [scijs/get-pixels](https://github.com/scijs/get-pixels) dependency. I opened an issue here: https://github.com/scijs/get-pixels/issues/57.

**Comment by donmccurdy** [comment]
Unfortunately there doesn't seem to be much to be done about this; it may be necessary to resize these images separately with a project like [sharp](https://sharp.pixelplumbing.com/). I'll keep an eye on the upstream bug on `get-pixels`.

**Comment by donmccurdy** [comment]
Related: https://github.com/donmccurdy/glTF-Transform/issues/358

**Comment by proto-ziii** [comment]
Hi @donmccurdy, I'm still encountering this issue (8k texture, memory exceeded) with the 2.1.5 release. 
I wonder if the @squoosh/lib integration should have fixed this? Also, I tried to run texture resize on  [gltf-Report](https://gltf.report/) with the same file and it worked just fine. Can you give me some hints here?

**Comment by donmccurdy** [comment]
Hi @proto-ziii! No changes have been made here, the summary is:

1. node.js has limited memory
2. the current resizing tool, [ndarray-lanczos](https://github.com/donmccurdy/ndarray-lanczos), is less memory-efficient than some alternatives in order to support both node.js and browser environments

I can't control the memory limits in browsers or node.js, so https://gltf.report/ may be able to access more memory than your node.js environment, or may have a lower memory footprint for other reasons.

More efficient resizers include [squoosh/lib](https://www.npmjs.com/package/@squoosh/lib) or [sharp.js](https://sharp.pixelplumbing.com/api-resize), and either could be used for custom versions of the [textureResize()](https://github.com/donmccurdy/glTF-Transform/blob/d455351/packages/functions/src/texture-resize.ts#L41) function. I'll likely switch to squoosh/lib for resizing only if a web build is published (https://github.com/GoogleChromeLabs/squoosh/issues/1084).

**Comment by proto-ziii** [comment]
I see. Will try to impliment the sharp.js. Thanks for the details and this awesome project!

**Comment by hybridherbst** [comment]
Just wanted to chime in that I've also ran into this now, found this issue, and hoping for squoosh/lib integration at some point :)

**Comment by donmccurdy** [comment]
/cc https://github.com/donmccurdy/glTF-Transform/issues/647

For folks running into this issue, the manual workaround for glTF files hitting this error would be to unpack the textures (if they aren't already separate) and resize large textures manually.

```
gltf-transform cp input.glb output.gltf
```

The number of textures and size of textures both contribute to memory limits, with ≤4K being generally recommended. Aim for powers of two on each side, like 512px, 1024px, or 2048px. The textures do not need to be square.

**Comment by timhc22** [comment]
Yes this worked for me, thanks for the response on Stack Overflow @donmccurdy, what I did, for anyone else interested, was: 

1. Use blender to save a HUGE gltf as a 'separate' file (so the texture is separate).
2. Use Photoshop/Gimp to resize the texture.
3. Re-import into blender
4. Export again as an embedded gltf
5. Run `npx gltfjsx ./myfile.gltf --types --shadows --transform --aggressive --draco https://www.gstatic.com/draco/versioned/decoders/1.4.1/` to squish it into a nicely sized glb file

When you do 5., the tsx generated might include a `.` in the file name, so either rename them in blender in step 3., or write typescript like so in the generated tsx:

```
type GLTFResult = GLTF & {
  nodes: {
    Mesh_0001: THREE.Mesh
  }
  materials: {
    'material_0.001': THREE.MeshBasicMaterial
  }
}
      <mesh castShadow receiveShadow geometry={nodes.Mesh_0001.geometry} material={materials['material_0.001']} />
```



https://blender.stackexchange.com/questions/270593/how-to-use-blender-to-get-model-to-a-state-where-it-can-be-shrank-with-gltfjsx?noredirect=1#comment464073_270593
