### ISSUE TITLE
Textures compressed to etc1s lose transparency info on Safari 15

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#446]
**Describe the bug**
Seems to be a Webkit bug, but I thought since the files are generated with gltf-transform I'd file this here as well so it can be tracked.
See https://github.com/google/model-viewer/issues/3024 for full description, file, and screenhots. 

![image](https://user-images.githubusercontent.com/2693840/144642992-52d3e2b3-ccb0-48aa-b5d3-3fcd545f4569.png)

I attached the original file that, when packed with gltf-transform etc1s, exhibits the issue: 
[Hexdomes.zip](https://github.com/donmccurdy/glTF-Transform/files/7651162/Hexdomes.zip)

The command to produce the file was just
```gltf-transform etc1s HexDomes.glb HexDomes.etc1s.glb```

Packing to uastc doesn't exhibit the same issue.

Webkit issue link: https://bugs.webkit.org/show_bug.cgi?id=232357

**Comment by donmccurdy** [comment]
Adding some cross-references:

- https://github.com/KhronosGroup/3D-Formats-Guidelines/issues/17
- https://github.com/google/model-viewer/issues/3024
- https://github.com/mrdoob/three.js/issues/22899

glTF-Transform is doing the right thing here, but the problem comes down to selecting the right transcode target in three.js, combined with unusually limited support for compressed transcode targets in Safari. As Alexey's comment in the 3D-Formats-Guidelines issue above mentions, more target formats will eventually work in Safari.
