### ISSUE TITLE
Add support for MSFT_LOD extension

### ISSUE THREAD

**Issue by Wellan-Arthur** [donmccurdy/glTF-Transform#530]
**Is your feature request related to a problem? Please describe.**
I am mostly working with MSFT_LOD ready renderers and I am looking for creating a good 3D asset pipeline to facilitate the asset production.

**Describe the solution you'd like**
It would be great to get MSFT_LOD added as part of the @gltf-transform/extensions package.
The ideal feature would be to merge 3D models of different LOD, sort them by vertex count (not required), and calculate, based on that, the ideal screen coverage(not required), then add the extension details (like screen coverage) to the model.

**Describe alternatives you've considered**
I have been able to make MSFT_LOD ready models just by using the merge CLI command and editing the json by hand, it's simple. I am also trying to create the extension myself, but I am fairly new to GLTF-transfom and lack the deep understanding of it required to do such a thing.

**Additional context**
MSFT_LOD require lods to be divided at the node or material level. Then add a few line to the LOD0 (the highest quality) to declare the extension and screen coverage details, and make sure the default scene only load LOD0.
Documentation :
https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/MSFT_lod

**Comment by donmccurdy** [comment]
Hi @Wellan-Arthur! I'm currently aiming to include all KHR extensions, and EXT extensions on a case-by-case basis. Just given the scope and maintenance required I'm not including vendor-specific extensions in this project (see [roadmap](https://gltf-transform.donmccurdy.com/contributing.html#roadmap)). The intention is very much to support development of those extensions outside the project though, and e.g. the OMI group has [developed a few extensions](https://github.com/omigroup/omi-gltf-transform) this way.

If you wanted to have a go at it, I'd suggest KHR_materials_variants [materials-variants.ts](https://github.com/donmccurdy/glTF-Transform/blob/9431e3aeec7d1bac01c31090b2c20fe5227a8146/packages/extensions/src/khr-materials-variants/materials-variants.ts) and [mapping-list.ts](https://github.com/donmccurdy/glTF-Transform/blob/9431e3aeec7d1bac01c31090b2c20fe5227a8146/packages/extensions/src/khr-materials-variants/mapping-list.ts) as a starting point, using a list of Nodes instead of a list of Mappings.

I'll leave the issue open for now, I suspect there may be other people interested in working with LODs.

**Comment by donmccurdy** [comment]
I've since written https://gist.github.com/donmccurdy/2226332bb58980caebcd21fe7cbca029, as an example to get started here. I don't currently plan to do more within this repository, and will close this issue.

/cc @takahirox
