### ISSUE TITLE
"Passthrough Mode" for custom extensions

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#543]
**Is your feature request related to a problem? Please describe.**
As custom extensions become more common, and glTF pipelines become the norm (in our case, using gltf-transform), there's a pratical issue: gltf-transform as CLI application doesn't keep custom extensions (it strips them out), and making a custom version that supports more extensions isn't quite trivial.

This also means that gltf-transform can't just be used as part of pipelines that deal with relatively arbitrary data: all extensions need to be known beforehand or are discarded.

**Describe the solution you'd like**
Many extensions are effectively "better extras" in the sense that they take what could have otherwise been packed in extras and put that into an extension, to have it better organized. Currently, the way gltf-transform operates means that this data gets lost on optimization, whereas keeping it in extras would have preserved it.

It would be great if there was a CLI flag and setting to basically treat extensions as "organized extras" and just passes them through untouched. I've seen 
- https://github.com/donmccurdy/glTF-Transform/pull/421

which seems to have done the opposite in the sense of correctness (e.g. what should happen when an extension uses extra buffers? pass them through untouched as well?). That flag would effectively say "treat all extension data that IO doesn't know about as important and keep it as-is".

**Describe alternatives you've considered**
Alternatives are either 
- fully implementing each used extension into gltf-transform, which seems like a lot of work to use pipeline features such as texture and mesh compression
- not using custom extensions, back to the stone age of cramming everything into extras

**Comment by donmccurdy** [comment]
The main limitation to a 'passthrough mode' that treats the extension data as opaque JSON would be that it cannot reliably preserve references: texture and node indices may change, buffer view byte offsets almost certainly will change, and then those references will break. Extensions containing no references are the exception rather than the rule (AFAIK)... do yours fit that criterial? I'm nervous to encourage developers down a path that hits a dead end as soon as they need to reference a texture. 

One idea I'm definitely interested in (see https://github.com/donmccurdy/glTF-Transform/issues/85, the title is misleading...) would be providing a way to supply custom extensions to the glTF Transform CLI _without_ needing to build a custom version of the CLI. Consider something like:

```shell
gltf-transform draco in.glb out.glb --plugins ~/.gltf-transform/
```

Or perhaps reading extensions from an external NPM package (possibly private).

In that scenario, the remaining question would be — how easy can we make it to implement "better extras"-type extensions without a lot of work? Looking at the [KHR_materials_unlit implementation](https://github.com/donmccurdy/glTF-Transform/tree/9431e3aeec7d1bac01c31090b2c20fe5227a8146/packages/extensions/src/khr-materials-unlit) I'd guess that's currently around 40 LOC. That doesn't seem crazy but perhaps could be improved.

Does any of that seem like a workable direction?

**Comment by hybridherbst** [comment]
Our main use case for gltf-transform right now is that it makes any combination of etc1s/uastc/draco/meshopt compression easy as part of a pipeline. I might not have the full picture, but I think for that texture and node indices will never change. I think even custom buffer views inside extensions could be rewritten after textures and meshes inside the same buffer have been shuffled around (but I'm not 100% sure).

I very much agree that such a "passthrough mode" could only reasonably be supported for a subset of gltf-transform operations, and not for all of them, e.g. only for etc1s/uastc/draco/meshopt compression. Would that be another option?

**Comment by donmccurdy** [comment]
> I might not have the full picture, but I think for that texture and node indices will never change...

Hm, the nodes part is currently true, but isn't something I can indefinitely guarantee for Meshopt. Compression starts with quantization, which creates or clones nodes and skins to hold quantization scaling factors.

Texture order isn't guaranteed to be stable for any operation – gltf-transform combines glTF's "texture" and "image" concepts into a shared [Texture](https://gltf-transform.donmccurdy.com/classes/core.texture.html) class to simplify the coding API surface. Image order is preserved in that process, but Texture order may be lost.

Similarly, gltf-transform always rewrites buffer views into one of its two included [vertex layouts](https://gltf-transform.donmccurdy.com/enums/core.vertexlayout.html). I think that's an area where it's better to be somewhat opinionated than to send through the original layout, which is often determined by whatever was convenient for the exporter.

The other ways of storing metadata — Extras or XMP packets — both lack stable internal references and would be appropriate for prototyping. Both are already supported here. But I don't think I want to put myself in a position where I'm trying to guarantee stable indices in opaque JSON blobs, it's pretty constraining and probably fragile. On the other hand I've put a lot of work into providing an extension API that supports custom extensions in userland and preserves their references — I think that's the route I would want to go here. That doesn't need to be a "full" implementation for every draft idea, you could hook up something like this pretty quickly I think:

```js
const io = new NodeIO()
  .registerExtension([
    ...KHRONOS_EXTENSIONS,
    createOpaqueExtension('DRAFT_node_events', PropertyType.NODE),
    createOpaqueExtension('DRAFT_node_selection', PropertyType.NODE),
  ]);
```

**Comment by donmccurdy** [comment]
Your vendor extensions will need to extend the [Extension](https://gltf-transform.donmccurdy.com/classes/core.extension.html) base class, and if you override the constructor be sure to call `super(document)` so it runs too. MaterialsUnlit is a good example to emulate:

https://github.com/donmccurdy/glTF-Transform/blob/9431e3aeec7d1bac01c31090b2c20fe5227a8146/packages/extensions/src/khr-materials-unlit/materials-unlit.ts#L45-L84

TypeScript notation is optional but the compiler hints make this much easier, sorry for the lack of documentation on that part! There's also a 'dummy' node extension in the unit tests that is nice and simple:

https://github.com/donmccurdy/glTF-Transform/blob/c4c7fe7fdaaf7dd8c03e028c13c794afecb927c0/packages/core/test/extension.test.ts#L7-L42

**Comment by donmccurdy** [comment]
I forgot TypeScript's version of class fields makes this non-obvious to port, here's a plain-JS version of the GizmoExtension above:

```js
const EXTENSION_NAME = 'DRAFT_nodes_gizmo';

class GizmoExtension extends Extension { 
    constructor(document) {
        super(document);
        this.extensionName = EXTENSION_NAME;
    }
    createGizmo() { 
        return new Gizmo(this.document.getGraph()); 
    } 
    write(context: WriterContext) { 
        for (const node of this.document.getRoot().listNodes()) { 
            if (node.getExtension(EXTENSION_NAME)) { 
                const nodeDef = context.jsonDoc.json.nodes[context.nodeIndexMap.get(node)]; 
                nodeDef.extensions = { TEST_node_gizmo: { isGizmo: true } }; 
            } 
        } 
        return this; 
    } 
    read(context) { 
        context.jsonDoc.json.nodes.forEach((nodeDef, index) => { 
            const extensionDef = nodeDef.extensions && nodeDef.extensions.TEST_node_gizmo; 
            if (!extensionDef || !extensionDef.isGizmo) return; 
            const extension = this.document.createExtension(GizmoExtension) as GizmoExtension; 
            context.nodes[index].setExtension(EXTENSION_NAME, extension.createGizmo()); 
        }); 
        return this; 
    } 
} 
GizmoExtension.EXTENSION_NAME = EXTENSION_NAME; 

class Gizmo extends ExtensionProperty { 
    constructor(graph) {
        super(graph);
    }
    init(): void { 
        this.extensionName = EXTENSION_NAME; 
        this.propertyType = 'Gizmo'; 
        this.parentTypes = [PropertyType.NODE]; 
    } 
} 
```

**Comment by marwie** [comment]
Thanks for the info. I've got a few steps further now but maybe it's better if I write this directly in typescript.

I've also ran into an issue where it tried to access the ``parentTypes``  array on the ExtensionProperty and threw because it hadn't called ``init`` - it looks like ``init()`` is never called actually. I'm not sure why tho.

I also had to pass the extension as a second argument to the Gizmo property because it threw errors without it as well as save ``this.document`` myself.

```js
const EXTENSION_NAME = 'NEEDLE_gameobject_data';
class NEEDLE_gameobject_data extends Extension {
	// EXTENSION_NAME: "NEEDLE_gameobject_data";
	constructor(document) {
		super(document);
		this.document = document;
		this.extensionName = EXTENSION_NAME;
		console.log(document !== undefined);
		// console.dir(document.getRoot());
		// document.getRoot()._enableExtension(this);
	}
	createGizmo() {
		const graph = this.document.getGraph();
		console.log("create gizmo", this.document !== undefined, graph !== undefined);
		return new Gizmo(graph, this);
	}

	write(context) {
		console.log("WRITE");
		for (const node of this.document.getRoot().listNodes()) {
			// console.log(node);
			if (node.getExtension(EXTENSION_NAME)) {
				const nodeDef = context.jsonDoc.json.nodes[context.nodeIndexMap.get(node)];
				console.log("WRITE", nodeDef);
				nodeDef.extensions = nodeDef.extensions || {};
				nodeDef.extensions[EXTENSION_NAME] = { isGizmo: true };
			}
		}
		return this;
	}
	read(context) {
		console.log("READ");
		context.jsonDoc.json.nodes.forEach((nodeDef, index) => {
			const extensionDef = nodeDef.extensions && nodeDef.extensions[EXTENSION_NAME];
			if (!extensionDef) return;
			console.log(extensionDef);
			const extension = this.document.createExtension(NEEDLE_gameobject_data);
			// extension.document = this.document;
			const gizmo = extension.createGizmo();
			const node = context.nodes[index];
			// console.log(node !== undefined);
			node.setExtension(EXTENSION_NAME, gizmo);
		});
		return this;
	}
};
NEEDLE_gameobject_data.EXTENSION_NAME = EXTENSION_NAME;

class Gizmo extends ExtensionProperty {
	constructor(graph, parent) {
		super(graph, parent);
		console.log("Created prop");
	}
	init() {
		console.log("INIT");
		this.extensionName = EXTENSION_NAME;
		this.propertyType = 'NEEDLE_gameobject_data';
		this.parentTypes = [PropertyType.NODE];
	}
}
Gizmo.prototype.parentTypes = [PropertyType.NODE]; // uncomment this to bypass error
Gizmo.EXTENSION_NAME = EXTENSION_NAME;

const io = new NodeIO()
	.registerExtensions(ALL_EXTENSIONS)
	.registerExtensions([NEEDLE_gameobject_data])
	.registerDependencies({
		'draco3d.decoder': await draco3d.createDecoderModule(),
		'draco3d.encoder': await draco3d.createEncoderModule(),
	});

async function packFile(file) {
	const document = io.read(file);
	document.getLogger().verbosity = 0;
	// document.createExtension(NEEDLE_gameobject_data);
	await document.transform( ....


```

This is how I invoke the script: ``node node_modules/needle.tiny.engine/plugins/gltf-packer.mjs``

**Comment by marwie** [comment]
Tried adding everything from init to the prototype directly, now I'm getting something in my glb!

```js
Gizmo.prototype.extensionName = EXTENSION_NAME;
Gizmo.prototype.propertyType = 'NEEDLE_gameobject_data';
Gizmo.prototype.parentTypes = [PropertyType.NODE]; // uncomment this to bypass error
Gizmo.EXTENSION_NAME = EXTENSION_NAME;
```

**Comment by donmccurdy** [comment]
It sounds like you might be using gltf-transform v1? The extension API did change a bit with v2, e.g. the `init()` method was added. Here's the same [Gizmo extension from v1](https://github.com/donmccurdy/glTF-Transform/blob/78cbc369b2808c2840a926c3ff57f397a6eb3f70/packages/core/test/extension.test.ts#L8-L39). 

That doesn't matter much for simple extensions with no references, but the syntax for internal references changed more, see examples in #437.

**Comment by marwie** [comment]
In node_modules versions are 2.1.1 (extensions, core, cli, functions)

**Comment by marwie** [comment]
Thanks for your help, I managed to build something that just passes our info through for now. Will most likely have to properly support reference handling at some point but as a first step it's great that is works again.

So for now implemented something like this (like you suggested above)
```js
	.registerExtensions([
		createOpaqueExtension("KHW_techniques_webgl", [PropertyType.NODE, PropertyType.MATERIAL]),
		createOpaqueExtension("NEEDLE_gameobject_data", PropertyType.NODE),
		createOpaqueExtension("NEEDLE_components", PropertyType.NODE),
		createOpaqueExtension("NEEDLE_timeline", PropertyType.NODE),
	])
```

**Comment by donmccurdy** [comment]
Glad to hear! Though still confused why `init()` did not run and the [ExtensionProperty](https://github.com/donmccurdy/glTF-Transform/blob/main/packages/core/src/properties/extension-property.ts) has an extra constructor parameter from circa v1.x ... 🤔 Anyway I'll leave this open for now – it does seem like some documentation on how to write a simple custom extension (in TS or JS) would be a good addition to these pages:

- https://gltf-transform.donmccurdy.com/extensions.html
- https://gltf-transform.donmccurdy.com/classes/core.extension.html
- https://gltf-transform.donmccurdy.com/classes/core.extensionproperty.html

And, since you're using NodeIO programmatically, it doesn't sound like you are looking for a way to plug these custom extensions up to the CLI package currently?

**Comment by marwie** [comment]
We dont need CLI support right now, no!

Btw is there a official way to read/write root asset extensions to the context (or does that not exist because it will never be transformed) ? We implemented a version of [KHR_techniques_webgl](https://github.com/KhronosGroup/glTF/blob/956b567029402792ab34122804050ce585603a03/extensions/2.0/Archived/KHR_techniques_webgl/README.md#extension) and I currently just pass it through manually (without adding it to the context)

**Comment by donmccurdy** [comment]
I'm not sure I followed `read/write root asset extensions to the context`, do you mean adding objects like KHR_techniques_webgl programs, shaders, and techniques to the "context" arguments passed to the extension during read/write? If so, that isn't necessary, the context exists only during a read/write process and doesn't need that information.

If not — two examples of extensions implemented here that involve top-level lists of objects, which might be helpful references:

- [KHR_materials_variants](https://github.com/donmccurdy/glTF-Transform/tree/ec6a85af4b588ad07b3482a5b341463329cc5a6d/packages/extensions/src/khr-materials-variants)
- [KHR_xmp_json_ld](https://github.com/donmccurdy/glTF-Transform/tree/ec6a85af4b588ad07b3482a5b341463329cc5a6d/packages/extensions/src/khr-xmp-json-ld)

**Comment by donmccurdy** [comment]
> Anyway I'll leave this open for now – it does seem like some documentation on how to write a simple custom extension (in TS or JS) would be a good addition ...

Filed a separate ticket, #559.

**Comment by marwie** [comment]
Regarding ``read/write root asset extensions`` you got it correctly. Thanks for clarifying

**Comment by donmccurdy** [comment]
Considering possible improvements here:

- https://github.com/donmccurdy/glTF-Transform/issues/1856
