### ISSUE TITLE
Resizing textures to 2k is broken for a particular model

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#562]
**Describe the bug**
While reducing texture sizes, I noted that a particular model produces wrong results in specific texture sizes; 2k breaks and 1k works. 

**To Reproduce**
1. Download https://drive.google.com/file/d/1zX2hyLozcOU5awRGSE01_NPtimz8qWzl/view?usp=sharing
2. Run `gltf-transform resize --width 2048 --height 2048 066.glb 066.2048.glb`
3. Run `gltf-transform resize --width 1024 --height 1024 066.glb 066.1024.glb`
4. View in [gltf.report](https://gltf.report)
5. Note that the 2048px version is broken while the 1024px version matches the original.

**Expected behavior**
Same appearance between 1024 and 2048px, and consistent with the input.

**Versions:**
 - Version: 2.1.4
 - Environment: tested in CLI and gltf.report

**Comment by donmccurdy** [comment]
Hm thanks! I think my resizing dependency (https://github.com/donmccurdy/ndarray-lanczos) is having trouble with some input/output ratios, like the 5464x3070 input here. I'm using that package because it works both on the web and in node.js, but there are much better (faster, more stable) alternatives for node.js, like [sharp](https://sharp.pixelplumbing.com/api-resize) or [squoosh/lib](https://www.npmjs.com/package/@squoosh/lib). If speed and memory footprint are an important concerns, you might want to try swapping out a couple lines here for a different resizing library:

https://github.com/donmccurdy/glTF-Transform/blob/a17b2964aeb6b2c34231fe5a3dfb29cd801888bc/packages/functions/src/texture-resize.ts#L79-L88

**Comment by donmccurdy** [comment]
I've been hoping `ndarray-lanczos` would be a temporary stopgap until squoosh/lib gets web support (https://github.com/GoogleChromeLabs/squoosh/issues/1084)...

**Comment by donmccurdy** [comment]
- /cc https://github.com/donmccurdy/glTF-Transform/issues/647
