### ISSUE TITLE
Instance not working using the JS package but working using CLI

### ISSUE THREAD

**Issue by Samsy** [donmccurdy/glTF-Transform#567]
**Describe the bug**
Did some tests with the instance function of the transform.

const extensionDef = nodeDef.extensions?.[this.name] does not seem to be filled using the instance function of the JS package.
But is working using the CLI command : gltf-transform instance untitled.glb output.glb 

const extensionDef = nodeDef.extensions?.[this.name] in the GLTFInstancingExtension of threejs is empty.

**To Reproduce**
Not working : 
1. Go to  https://gltf.report/
2. Drag a GLB that has multiple same references
3. Go to script
4. import instance from the functions and add it in the document transform

Working : 

1. Use cli command : 
gltf-transform instance untitled.glb output.glb  on a GLB that has multiple same references
2. Go to  https://gltf.report/
3. Drag the output in

**Comment by donmccurdy** [comment]
Hi! The code in [`instance.ts`](https://github.com/donmccurdy/glTF-Transform/blob/main/packages/functions/src/instance.ts) is the same, and the CLI invocation is doing nothing special:

https://github.com/donmccurdy/glTF-Transform/blob/0bae984aed869d5d03ac24c3005830216ab241e0/packages/cli/src/cli.ts#L357-L362

Do you see any warnings while writing the file, or could you share an example input file? Is there anything else unusual in the file, like multiple external `.bin` files?

**Comment by Samsy** [comment]
This link is a a drive to a test file which is a very simple duplication of 5 cubes in blender

[](https://drive.google.com/file/d/1j0Jc2uaMryPpshrB8cWfyIn1paawa7-a/view?usp=sharing)


Using the JS API and the EXT_mesh_gpu_instancing in a GLTF loader : 

With the GLTF TRANSFORM JS API for instancing : 

<img width="1380" alt="Capture d’écran 2022-04-22 à 18 21 35" src="https://user-images.githubusercontent.com/3786958/164755557-8f2239ea-e3db-44b0-8ed6-9d3da78b97a9.png">

With the GLTF COMMAND LINE API for instancing : 

<img width="1389" alt="Capture d’écran 2022-04-22 à 18 20 19" src="https://user-images.githubusercontent.com/3786958/164755620-0d6b561b-36c3-4d78-ab83-6f51441deecd.png">

**Comment by donmccurdy** [comment]
I'm getting identical files from the CLI and the browser, exclusive of JSON whitespace:

| web | cli |
|---------|-----|
| ![browser](https://user-images.githubusercontent.com/1848368/164764253-ef838096-07e6-45ca-a1ee-e6836b3cb48e.png) | ![cli](https://user-images.githubusercontent.com/1848368/164764256-56c67630-8895-4f54-8da7-2509afe48c2c.png) |

Testing both files in https://sandbox.babylonjs.com/, they appear correctly:

![Screen Shot 2022-04-22 at 1 29 26 PM](https://user-images.githubusercontent.com/1848368/164764850-8493fe55-d6eb-4b91-9edc-f625ec6db47e.png)

If you're using the JS API in a custom application, be sure to register all extensions with the WebIO or NodeIO instance before writing the file. gltf.report will do this automatically.

Otherwise this might need to be reported on the GLTFInstancingExtension perhaps?

**Comment by Samsy** [comment]
Yes alright, 
It needed to register the MeshGPUInstancing extensions into the webIO / nodeIO.
I missed that part and thought webIO / nodeIO would only be for reading / writing files ! 

Thanks a lot for helping 🥷🏼
