### ISSUE TITLE
Compressing textures with KTX fails

### ISSUE THREAD

**Issue by kitaedesigns** [donmccurdy/glTF-Transform#590]
**Describe the bug**
"gltf-transform uastc" or "gltf-transform etc1s" returns "error: Cannot convert undefined or null to object"

**To Reproduce**
Run these commands to encode textures in .glb with ktx compression.

**Expected behavior**
New models with ktx compression should populate but job never finishes.

**Versions:**
 - Latest version of gltf-transform
 - KTX 4.0.0
 - Node.js 16.14.0

**Additional context**

Model Link
https://drive.google.com/file/d/1yWpxNgE6DeZPuwPPrRNfMHRIc-90P8Qb/view?usp=sharing

**Comment by donmccurdy** [comment]
If you run `toktx --version` do you get output? I'd expect to see something like `toktx v4.1.0-rc1~77`. Otherwise you may need to run the installer at https://github.com/KhronosGroup/KTX-Software/releases and make sure the tools are in the $PATH. 

The CLI is supposed to give a better error message though, to warn you that toktx was not found, so that's a bug I'll investigate.

**Comment by kitaedesigns** [comment]
"D:\Projects\GLBdex\source\glbdex\src\media\models>toktx --version
'toktx' is not recognized as an internal or external command,
operable program or batch file." 

No output, hmm I installed KTX 4.0 for all users, I will try reinstalling and making sure they are in the correct $PATH

**Comment by donmccurdy** [comment]
Hm I'm not sure what would cause this, does it tell you where your `toktx` file eventually gets installed? The problem seems specific to installing KTX-Software on a Windows operating system, so it may be worth following up on the KTX-Software repo or even https://superuser.com/ ... there may be some way to manually add the folder to your $PATH if the KTX-Software installer cannot (e.g. for lack of system permissions).

**Comment by kitaedesigns** [comment]
I think you're right and it's a problem with the KTX installer. The strange thing is that the files are installed correctly but the PATH seems to still be missing.
![image](https://user-images.githubusercontent.com/23407511/169903773-721a4419-2973-428a-b799-bf82e718aa71.png)

**Comment by kitaedesigns** [comment]
I've filed a bug report on the KTX repo.

**Comment by donmccurdy** [comment]
> The CLI is supposed to give a better error message though, to warn you that toktx was not found, so that's a bug I'll investigate.

Fixed in v2.2.2, thanks!
