### ISSUE TITLE
Allow setting `keepLeaves: true` for the use of `prune` in `reorder` and `quantize`

### ISSUE THREAD

**Issue by dmliao** [donmccurdy/glTF-Transform#683]
**Is your feature request related to a problem? Please describe.**
For a project I'm working on, I've been creating GLTFs with named empty nodes to use as anchors for the app to later interact with. Using `quantize` or `reorder` to optimize the GLTFs cause them to break because those empty nodes get stripped out.

Initial investigation suggests that it's from the use of the `prune` function within those functions; `prune` has an option `keepLeaves`, which if set to `true` will neatly solve my problem, but as of right now it's difficult to access the options for the use of `prune` from within other functions.

**Describe the solution you'd like**
Either the options for `prune` be exposed in the functions that use it, or some way to change `PRUNE_DEFAULTS` from within the gltf processing step so I can set the default of `keepLeaves` to true.

**Describe alternatives you've considered**
Main workaround I've used until now is to modify the built `functions.js` file in the npm package to change `keepLeaves` in `PRUNE_DEFAULTS`, but that's fairly brittle.

**Additional context**
Mostly submitting this issue to discuss exactly how this problem should be solved; I have a few tentative solutions...the one with the least code changes would be to export `PRUNE_DEFAULTS`, so that it can be changed client-side, but that might not be desired. Any opinions or suggestions are welcome.

**Comment by donmccurdy** [comment]
Hi @dmliao! Are you able to reproduce the problem in the most recent v2.4.3 release? My intention was that the `keepLeaves` option would have an effect only if nodes are among the property types being pruned. In both quantize() and reorder(), nodes are not supposed to be affected:

https://github.com/donmccurdy/glTF-Transform/blob/f970b47864630a33a404edf9d5b99c6ef9ad0a59/packages/functions/src/quantize.ts#L120-L123

https://github.com/donmccurdy/glTF-Transform/blob/f970b47864630a33a404edf9d5b99c6ef9ad0a59/packages/functions/src/reorder.ts#L90-L91

However, in a prior release, leaves may have been removed despite that. I believe the issue was fixed in https://github.com/donmccurdy/glTF-Transform/pull/679.

**Comment by dmliao** [comment]
Ah, yes. I was on v2.4.1. Upgrading to v2.4.3 fixed it. Thank you!
