### ISSUE TITLE
Simplify: Relationship between 'error' and 'ratio'?

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#719]
**Describe the bug**
Since #655 there's a "simplify" command, however, it seems to not respect the "ratio" parameter at all (neither with nor without also specifying the error parameter).

![image](https://user-images.githubusercontent.com/2693840/200143805-9a31f92f-337f-427b-956c-4638bb97adb8.png)

**To Reproduce**
1. Download https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/DragonAttenuation/glTF-Binary/DragonAttenuation.glb
2. Run `gltf-transform simplify --ratio 0.1 DragonAttenuation.glb DragonAttenuation.simplified.glb`
3. Repeat with varying values of `--ratio`
4. Will always end up at the same file size and vertex count

**Expected behavior**
According to `help simplify` changing `ratio` should reduce the vertex count. Changing `error` does something, but _then_ changing `ratio` also does nothing.

**Versions:**
 - Version: v2.4.5
 - Environment: Node.js CLI

**Additional context**

Besides the issue at hand, it's interesting how the dragon's backdrop is/is not optimized - looks like coplanar vertices don't get merged at all? (this is with a very high "error" value)
![image](https://user-images.githubusercontent.com/2693840/200143769-6504f50b-187c-4dac-9447-5979eb4446b0.png)

**Comment by donmccurdy** [comment]
This feature is based on the meshoptimizer simplifier (by @zeux) — I'm not sure of the interaction between ratio and error myself, other than this line in the docs:

> ... the algorithm tries to simplify the mesh down to the target index count while maintaining the appearance error below acceptable error.

In practice it usually seems like the error, and not the ratio, is the more effective knob to turn. I don't think it's possible to omit either value, it just falls back to defaults if error is not specified. 

> Besides the issue at hand, it's interesting how the dragon's backdrop is/is not optimized - looks like coplanar vertices don't get merged at all? (this is with a very high "error" value)

If you haven't already, try doing a `weld` before running the `simplify` command — I believe the simplifier tries to preserve topology, so if vertices are not welded yet, it isn't going to merge them.

**Comment by zeux** [comment]
The ratio is simplification target - the simplifier will try to reach the target number of triangles, minimizing the error.

There are cases when the target can't be reached without significant degradation of quality. The error limits the degradation of quality; the simplifier will always reach the target with minimal error, but if the error exceeds the error threshold, it will stop short of the target ratio.

Note that the error is a mandatory parameter. I'm not actually sure what happens if you don't pass it in (whatever the rules are for undefined => wasm double conversion...), I'll add an assertion for the valid error range to the JS wrapper.

**Comment by hybridherbst** [comment]
Thanks for the explanations!

So if I understand that correctly, if my goal is "1000 vertices", then I must set the allowed error very high so that I actually end up at that vertex count.
Conversely, when my goal is "reduce this to some error, I don't care about vertex count", then I should set ratio to 0 and just let the error metric be the stop condition.
It seems it's rarely useful then to "mix" ratio and error in practice – I may neither get the desired error nor the desired vertex count when both are set to meaningful values. I believe it makes sense that way, just needs better documentation.

@donmccurdy I think it would at least help if the inline docs would point out the relationship more, maybe even with examples like "if you want to ensure this vertex count, make sure error is <some high number>" and "if you want to reduce up to a specific error irrespective of vertex count, specify ratio=0". Does that make sense?

**Comment by zeux** [comment]
> So if I understand that correctly, if my goal is "1000 vertices", then I must set the allowed error very high so that I actually end up at that vertex count.

Yeah, that's right, although there's also cases where topological restrictions prevent the simplification to desired target no matter what the error is. This might be improved in the future, and that's why in glTF-Transform, welding should be done in concert with simplification.

> Conversely, when my goal is "reduce this to some error, I don't care about vertex count", then I should set ratio to 0 and just let the error metric be the stop condition.

Yeah, that's exactly right. Setting target to 0 is a great way to simplify towards the acceptable error.

> It seems it's rarely useful then to "mix" ratio and error in practice – I may neither get the desired error nor the desired vertex count when both are set to meaningful values. I believe it makes sense that way, just needs better documentation.

It can be useful to prevent catastrophic degradation in quality - in a sense, this allows the target to be a "soft" parameter. For example, when generating an LOD chain, you might want each successive LOD level to be 50% of the previous one, but you also might be okay with a smaller reduction if attempting to reduce to 50% would penalize the quality too much.

**Comment by hybridherbst** [comment]
Mind adding that to the meshoptimizer docs as well? I think it's very useful info on how these parameters relate and what to expect / how to use them!

**Comment by donmccurdy** [comment]
Thanks @hybridherbst and @zeux! Hopefully https://github.com/donmccurdy/glTF-Transform/pull/725 improves the documentation here, comments welcome. :)
