### ISSUE TITLE
Support user-specified commands and extensions in CLI

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#85]
For example, accept a folder path as a global option, or use `~/.gltf-transform`. Ideally it load scripts in that folder and let them add new commands to the CLI by accessing the `program` variable, or register custom extensions to enable support in existing commands.

Examples:

```shell
# custom command
gltf-transform fooBar input.glb output.glb --plugins <plugin-path>

# custom extension
gltf-transform draco input.glb output.glb --plugins <plugin-path>
```

```js
program.option('-p, --plugins <path>', 'Plugin directory path.', {
	global: true,
	default: '~/.gltf-transform',
});
```

Vue CLI uses naming conventions to resolve plugins: https://cli.vuejs.org/dev-guide/plugin-dev.html#naming-and-discoverability. The code [looks a bit complicated](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/Service.js), though.

**Comment by donmccurdy** [comment]
Or extensions... maybe just check env variables?

**Comment by donmccurdy** [comment]
Vue CLI uses naming conventions to resolve plugins: https://cli.vuejs.org/dev-guide/plugin-dev.html#naming-and-discoverability. The code [looks a bit complicated](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/Service.js), though.

**Comment by donmccurdy** [comment]
I'd like to get this done in glTF Transform v3, perhaps later this month.

Rather than doing a "plugins path" as described above, I might prefer to have users specify a config file, in the style of `rollup.config.js`, `vite.config.js`, `webpack.config.js`, etc.

Invocation:

```bash
gltf-transform --help --config path/to/config.js
```

Output would then list all commands including those registered by the configuration. A configuration would be defined as follows:

```javascript
import { Session } from '@gltf-transform/cli';
import { acme } from './src/acme.js';

export default {
  extensions: [
    ACMECustomExtension1,
    ACMECustomExtension2,
  ],
  dependencies: {
    'acme.decoder': createDecoder(),
    'acme.encoder': createEncoder(),
  }
  onProgramReady: ({program, io}) => {
    program
      .command('acme', 'ACME custom command')
	.help('Lorem ipsum dolorem...')
	.argument('<input>', 'Path to read')
	.argument('<output>', 'Path to write')
	.option('--bake', 'Whether to bake', {
		validator: program.BOOLEAN,
		default: false,
	})
	.action(({args, options, logger}) =>
		Session.create(io, logger, args.input, args.output)
			.transform(acme(options as PartitionOptions))
	);
  }
}
```

Code above is still subject to change, and open for feedback.

**Comment by donmccurdy** [comment]
Possible alternative propsed by @bhouston —

> Look at prettier and eslint extensions, they are JS/TS npm modules you install side by side with the main tool.  Then you reference them by name in the *.rc/.json file and put their configs in there.
> 
> This is then the default for your command line executions.

https://mastodon.gamedev.place/@BenHouston3D/109660130920789099

***

There are some things we'd need to figure out with that approach:

1. Can users define commands and extensions locally, without publishing an npm package?
2. How does glTF Transform 'discover' the extensions, given their names? Just do a dynamic import and let node.js module resolution figure it out?

**Comment by bhouston** [comment]
Here is eslint's documentation for plugins:

https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new#using-plugins-in-your-configuration

It seems that you can use imports at the top of the file and then use the resolved module in the plugin section:

```js
import jsdoc from "eslint-plugin-jsdoc";

export default [
    {
        files: ["**/*.js"],
        plugins: {
            jsdoc
        },
        rules: {
            "jsdoc/require-description": "error",
            "jsdoc/check-values": "error"
        }
    }
];
```

Since you control the import here, then you can pull it in from a development environment.

This is in contrast to the older style of eslint configuration files that only used names that had to be resolved via the package.json file: https://eslint.org/docs/latest/user-guide/configuring/plugins

**Comment by donmccurdy** [comment]
Work in progress:

- https://github.com/donmccurdy/glTF-Transform/pull/791

Feedback would be welcome, see the sample config in the PR for an example. The goal here is that the user can register custom extensions (e.g. `ACME_materials_lightmap`) and custom commands used for CLI processing.

For example — if someone implemented lightmap baking in a new package, it could be registered for use with the glTF Transform CLI, without needing to fork the entire commandline tool. 

```
gltf-transform bake input.glb output.glb
```

```javascript
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';
import { bake, ACMEMaterialsLightmap } from './path/to/bake.js';

export default {
  extensions: [...ALL_EXTENSIONS, ACMEMaterialsLightmap],
  onProgramReady: ({program, io, Session}) => {		
	program
	.command('bake', 'Bake lightmaps')
	.help('Lorem ipsum dolorem...')
	.argument('<input>', 'Path to read glTF 2.0 (.glb, .gltf) model')
	.argument('<output>', 'Path to write output')
	.action(({ args, options, logger }) =>
		Session.create(io, logger, args.input, args.output)
			.transform(bake(options))
	);
  }
}
```

The main obstacle I'm seeing so far is that handling both CJS and ESM configs will require some work. I'd like to move toward supporting only ESM (#620). If that can be done in v3 it would simplify implementation here.

**Comment by donmccurdy** [comment]
CLI has been migrated to ESM:

- #799 
- #798

**Comment by hybridherbst** [comment]
Hey, I tried to test your PR (#791) but ran into the aforementioned ESM issues that I see are fixed now. Would you mind rebasing that PR on latest? I tried but had a few conflicts with imports that I wasn't sure how to correctly resolve (and naive resolution didn't work).

**Comment by hybridherbst** [comment]
Hey @donmccurdy, thanks! I played around a bit and was able to port @takahirox' MSFT_lods generator to use `--config`: https://github.com/needle-tools/glTF-Transform-lod-script/blob/main/generate_lod.js

It's nice that multiple commands can be in the same config;
it's also nice that args can be provided, albeit I'm not super sure yet what the restrictions are (e.g. can I pass in `--ratio 1 2 3 4` or should it be one arg, e.g. `--ratio 1,2,3,4`).

Added some info on what I did and what the command is here: https://github.com/needle-tools/glTF-Transform-lod-script/tree/main#how-to-use
And here's my test file, currently ratios and so on are hardcoded in the config file:
[ComplexPlaneTopology.zip](https://github.com/donmccurdy/glTF-Transform/files/10676254/ComplexPlaneTopology.zip)

I did get one Windows-specific path error:
In config.ts I had to add "file://" because otherwise there were errors about node treating drive letters in absolute paths (e.g. "F;//My/Path" as protocol (?) and complaining because "f://" is not a valid protocol. "file://" made that work.
![image](https://user-images.githubusercontent.com/2693840/217277090-c9e25a39-33f5-4484-9da6-35895f9b792c.png)

**Comment by donmccurdy** [comment]
> albeit I'm not super sure yet what the restrictions are...

The arg handling is provided by Caporal (https://caporal.io/guide/#commands), if you set `validator: program.ARRAY` on the option, it will try to split strings by commas. I think something like `--ratio 1 --ratio 2 --ratio 3 ...` would also be accepted. Caporal's maintenance seems to have dropped off this past year, though, so perhaps I should wrap its `program` interface to future-proof this.

All the current usage examples are here:

https://github.com/donmccurdy/glTF-Transform/blob/main/packages/cli/src/cli.ts

> I did get one Windows-specific path error ...

Ah that's good to know, thanks! I'll take a look at that, hopefully `file://` is OK on macOS too.

**Comment by donmccurdy** [comment]
@hybridherbst I can't seem to find any documentation about `file://` protocol being a thing in Node.js dynamic imports, but there is `file:` prefix with the same idea. I've pulled that change into #791, do you mind testing that it works on Windows as well?

**Comment by donmccurdy** [comment]
Note to self -- autodiscovery of plugins would probably be a bad idea. See PR in which Prettier has removed that feature: https://github.com/prettier/prettier/pull/14759.
