### ISSUE TITLE
dedup: performance is not defined

### ISSUE THREAD

**Issue by Ivolutio** [donmccurdy/glTF-Transform#866]
**Describe the bug**
I keep getting the error 'performance is not defined' when I try to run the optimize command on my local pc. It works for my colleague but I can't find why it doesn't work for me.

**To Reproduce**
1. `npm install --global @gltf-transform/cli`
2. `gltf-transform optimize ./temp.glb ./output.glb`
3. Error: 
```
× dedup: performance is not defined
error: performance is not defined
```

**Versions:**
 - Version: v3.1.1
 - Environment: Windows 11, Node.js v14.19.0

**Comment by donmccurdy** [comment]
Do you see this error if you try to run other commands like `copy` instead of `optimize`? 

I think this may be an issue only on versions of Node.js older than v16. If you can update to v16 or v18 that should work around the issue, but I do intend to support v14 so I'll try to get that fixed. Thanks!

**Comment by donmccurdy** [comment]
Glad to hear, and thanks for checking! :)
