### ISSUE TITLE
Splitting of skeleton bones after quantization

### ISSUE THREAD

**Issue by gtolarc** [donmccurdy/glTF-Transform#880]
When quantization is performed, the skeleton bones of a character animation created with CC4 will be broken into multiple pieces.
Each group of split bones are duplicates of the same content, but they seem to be being used because the amount of active bones has increased. Why is this happening and is there a way to fix it?
If I exclude POSITION from the quantization pattern, this goes away.

(before)
![Screenshot 2023-03-28 at 14 58 30](https://user-images.githubusercontent.com/8623798/228143022-9dba6311-33ca-4d42-9204-fdc34830089f.png)

(after)
![Screenshot 2023-03-28 at 14 58 57](https://user-images.githubusercontent.com/8623798/228143040-01bcd0d0-1083-4bdd-b75d-6efc304d2487.png)

**Comment by donmccurdy** [comment]
Could you share an example source file, before applying quantization? I'm not sure what CC4 is sorry!

**Comment by gtolarc** [comment]
> Could you share an example source file, before applying quantization? I'm not sure what CC4 is sorry!

This is a simple CC4 GLB export file created with a common sample character. Running this file with just the default simple quantization causes the problem I was talking about.
https://d.pr/f/GZVokb

![Screenshot 2023-03-31 at 10 21 10](https://user-images.githubusercontent.com/8623798/228999197-04c007d9-6ec6-4bf3-88f4-c6ba0706af58.png)
![Screenshot 2023-03-31 at 10 21 36](https://user-images.githubusercontent.com/8623798/228999201-a4d2bfff-17a9-4a6a-abc3-a566811320ee.png)
In the same scene, you can see that the active bones have increased.

I would like to programmatically fine-tune the ktx+meshopt compression, but this issue is causing it to be less optimized than the results of compression with the gltfpack cli tool.

I think the output from the flow below should be similar to the output from the gltfpack cli (-cc -tc -tq 10 -tp -si 0.99 -mm -mi), but I'd like to know if this is correct.
dedup -> instance -> weld(error=0.01) -> simplify(error=0.01) -> resample -> prune -> sparse -> toktx -> reorder -> quantize

**Comment by donmccurdy** [comment]
What's happening here is that quantization takes each mesh, scales it to fit within a [-1,1] box for better compression, and then sets a corrective scale and offset to the node referencing that mesh, so that it keeps its original world scale when rendered. For skinned meshes, the corrective scale and offset are applied to the inverse bind matrices of the skin, rather than to a node. This scene contains three meshes sharing the same skin, but because each has a different quantization transform, different inverse bind matrices are required for each mesh. This doesn't actually change the number of bones — it's still 73 — but it looks like babylon.js considers these to be new bones if they're used with different inverse bind matrices.

Anyway, the fix requires two things:

1. Quantize using the scene bounds, rather than mesh bounds. This option is already available:

```
gltf-transform quantize in.glb out.glb --quantization-volume scene
```

This ensures that each skin has the same inverse bind matrices after quantization.

2. Remove the the duplicate skins.

Probably (2) should be automatic, but it isn't yet. Probably the first step would be making sure that dedup() can detect and remove duplicate skins, I'll add that in https://github.com/donmccurdy/glTF-Transform/pull/883. Then possibly we can make sure that quantization will avoid creating the additional skins to begin with in this case.

It'll still be necessary to set the quantization volume to "scene", however. It doesn't appear to matter much in this case, but for some models quantizing to individual meshes performs much better.

**Comment by gtolarc** [comment]
I updated it and followed your instructions and it seems to be working fine, thank you! @donmccurdy
