### ISSUE TITLE
Draco compression breaks UV coordinates of mesh (?)

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#936]
**Describe the bug**
Ran into a weird issue with a photogrammetry mesh today.

This one:
![image](https://user-images.githubusercontent.com/2693840/236515337-7ca61094-27eb-4668-a6db-1c58490e65a7.png)

turns into a grey mush when run through
`gltf-transform draco file.glb file.draco.glb`
![image](https://user-images.githubusercontent.com/2693840/236515303-7d6299cf-7969-40be-b94c-b3043d96e890.png)

**To Reproduce**
1. Download [file.zip](https://github.com/donmccurdy/glTF-Transform/files/11408340/file.zip)
2. Run `gltf-transform draco file.glb file.draco.glb`
3. Look at file
4. Note texture is still there despite how it looks, but seems UVs are broken

**Expected behavior**
Model still looks mostly the same after applying draco compression

**Versions:**
 - Version: [3.2.1]
 - Environment: [CLI]

**Comment by donmccurdy** [comment]
Opening the UV layout in Blender, I'm seeing:

![Screenshot 2023-05-05 at 1 11 02 PM](https://user-images.githubusercontent.com/1848368/236522827-dedc49b8-7d84-419e-a83b-ddb122b744b4.png)

That diagonal line goes out to something like 10^38. Draco relies on quantization, so I think what's happening here is that the "normal" UVs are lost in the noise because of the large quantization grid required to fit these outlying UVs. You'll see the same result running this file through glTF Pipeline for Draco compression as well.

Quantization or Meshopt compression will succeed, but only because I haven't implemented support for quantizing UVs outside of the [0,1] range yet ... once that is implemented, I would expect both to give the same grey mush output, too.

Not sure much can be done here to detect and handle this situation, unfortunately. I wonder if there's some practical range that glTF Validator should allow for UVs, and warn if it exceeded? But perhaps any threshold would be arbitrary.

**Comment by hybridherbst** [comment]
Hmm, interesting. Since this is a photogrammetry mesh, I'd assume that the UVs are generated by some algorithm, and that a division by zero got clamped to some max - I do think some threshold would help here. I haven't seen files in practice that use UVs outside day, 10³... So I guess "half of float max" would be a reasonable assumption as sanitization threshold for kicking outliers?

**Comment by donmccurdy** [comment]
In theory the same thing could happen for vertex positions, e.g. putting an "unused" mesh out at x=999999. Currently scanning the file for problems isn't part of this project's scope. That would be an interesting idea, but I wouldn't be sure how to separate the scope from that of glTF Validator...

**Comment by hybridherbst** [comment]
Understood. My opinion would be a bit different: in cases like this it's not a validation issue, it's a data issue ("NaN in disguse") and most people running into it would not know how to fix it even if a validator told them. But, I agree, I can't think of a good rule of thumb / threshold on when data like this would be sanitized and when not.

**Comment by donmccurdy** [comment]
Perhaps the way to go here — rather than a threshold — would be to compute a histogram over the data, and warn if the histogram has extreme outliers like these. I don't really want to throw that into the draco processing step — I don't have enough insight into the Draco heuristics to really know what it can/can't handle, and computing histograms on vertex data is a costly thing to do for what appears to be a rare issue. 

I could imagine building a new command (similar to "brew doctor") that checks for and attempts to fix known issues, but that's a chunky addition to the scope of the project, and I don't have time/funding to throw at it currently.
