### ISSUE TITLE
Default PNG compression should be lossless

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#969]
I think it's reasonable to expect that PNG compression is lossless by default. That's what I'd always intended the default to be here, but reports (https://github.com/KhronosGroup/glTF-Sample-Models/pull/366) have found that it is not. Tracking that down further, it appears that passing `{quality: 100}` to Sharp is different than passing `{}`, even though quality=100 is the [defined default](https://sharp.pixelplumbing.com/api-output#png). The former enables palette compression, and will be particularly lossy for gradients.

Unless the user has specified options otherwise, the CLI and function should be lossless, presumably passing `{}` to Sharp.

**Comment by donmccurdy** [comment]
This is a bit of a rough spot in the Sharp API from my perspective. I think the safest thing I can do would be to _omit_ the defaults from my own API, and ensure that things get passed into Sharp as expected.

**Comment by jo-chemla** [comment]
Hi there, sorry to revive a closed thread. 

I think I'm experiencing this case specifically, in [this context](https://github.com/playcanvas/splat-transform/issues/38#issuecomment-3209783058), trying to convert textures from webp to png via the `gltf-transform png` CLI. When I specify the `--quality 100` flag in order to get lossless PNG, they are in fact lossy, and I have to avoid passing that flag to get lossless PNG. 

Or is there another flag that should be passed to the png CLI or sharp to avoid compressing the palettes? Below is the command run on the same input dataset with webp textures, with and without the quality 100 flag. 

```bash


C:\test\splat-compression>gltf-transform png sog-skeleton-metadata.glTF helicopter-png-q100_2/helicopter-png.glTF --formats * --slots * --quality 100 --verbose
warn: Missing optional extension, "SOG_attributes".
warn: Missing optional extension, "KHR_gaussian_splats_compression_sogv2".
debug: textureCompress(helicopter/means_l.webp): Format = webp → png
debug: textureCompress(helicopter/means_l.webp): Slots = []
...
debug: textureCompress(helicopter/means_l.webp): Size = 1.89 MB → 670.39 KB
debug: textureCompress: Complete.
info: sog-skeleton-metadata.glTF (10.07 MB) → helicopter-png.glTF (4.17 MB)

C:\Users\jonathan\Downloads\splat-compression>gltf-transform --version
4.2.1

C:\test\splat-compression>gltf-transform png sog-skeleton-metadata.glTF helicopter-png-q100_2/helicopter-png.glTF --formats * --slots * --verbose
warn: Missing optional extension, "SOG_attributes".
warn: Missing optional extension, "KHR_gaussian_splats_compression_sogv2".
debug: textureCompress(helicopter/means_l.webp): Format = webp → png
debug: textureCompress(helicopter/means_l.webp): Slots = []
debug: textureCompress(helicopter/means_l.webp): Size = 1.89 MB → 2.36 MB
...
debug: textureCompress: Complete.
info: sog-skeleton-metadata.glTF (10.07 MB) → helicopter-png.glTF (12.54 MB)


```
